// generated by mBlock5 for mBot Ranger
// codes make you happy
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include <MeAuriga.h>

MeUltrasonicSensor ultrasonic_10(10);
MeBuzzer buzzer;

void setup() {
  Serial.begin(9600);
  buzzer.setpin(45);
  while(1) {
      if(ultrasonic_10.distanceCm() < 10){
        Serial.print("TAKE_PICTURE");
        collisionBuzz();
      }
  }  
}

void collisionBuzz() {
  buzzer.tone(200, 50);
  delay(50);
  buzzer.tone(150, 100);
  delay(100);
  buzzer.tone(200, 50);
  delay(50);
  buzzer.tone(150, 100);
  delay(100);
  buzzer.tone(200, 50);
  delay(50);
  buzzer.tone(150, 100);
  delay(100);
}

